appId: tech.auxillo.auxprotondrivebridge
productName: Aux Proton Drive Bridge
artifactName: ${productName}-${version}-${arch}.${ext}
directories:
  output: dist
  buildResources: assets
files:
  - src/**/*
  - assets/**/*
  - package.json
  - README.md
asar: true
compression: normal
linux:
  target:
    - AppImage
    - deb
    - rpm
  category: Network
  executableName: aux-proton-drive-bridge
  icon: assets/icon.png
deb:
  depends:
    - libsecret-1-0
    - xdg-utils
rpm:
  depends:
    - libsecret
    - xdg-utils
